services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  service1:
    build: ./service1
    ports:
      - "5001:5001"


 
  service9:
    build: ./service9
    ports:
      - "5009:5009"     