services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  service1:
    build: ./service1
    ports:
      - "5001:5001"

  service6:
    build: ./service6
    ports:
      - "5006:5006"


