services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"

  service1:
    build: ./service1
    ports:
      - "5001:5001"
  service4:
    build: ./service4
    ports:
      - "5004:5004"


